---

- name: "Deploy Prometheus" 
  hosts: logging
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
  roles:
    - install-docker-dockercompose
    - install-prometheus-compose

  environment:
    ENVIRONMENT: production
    EC2_ACCESS_KEY: "{{ lookup('env', 'EC2_ACCESS_KEY') }}"
    EC2_SECRET_KEY: "{{ lookup('env', 'EC2_SECRET_KEY') }}"
    NODE_EXP_TARGET_URL: "{{ lookup('env', 'NODE_EXP_TARGET_URL') }}"
    TELEGRAM_ADMIN: "{{ lookup('env', 'TELEGRAM_ADMIN') }}"
    TELEGRAM_TOKEN: "{{ lookup('env', 'TELEGRAM_TOKEN) }}"
    
