---

- name: "Deploy Prometheus" 
  hosts: logging
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
  
  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      wait_for:
        port: 22
        host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
        search_regex: OpenSSH
        timeout: 600
        delay: 10
      connection: local

    - name: "install python for Ansible."
      raw: 'sudo apt -y install python3'

  roles:
    - install-docker-dockercompose
    - install-prometheus-compose

  environment:
    ENVIRONMENT: production
    EC2_ACCESS_KEY: "{{ lookup('env', 'EC2_ACCESS_KEY') }}"
    EC2_SECRET_KEY: "{{ lookup('env', 'EC2_SECRET_KEY') }}"
    NODE_EXP_TARGET_URL: "{{ lookup('env', 'NODE_EXP_TARGET_URL') }}"
    TELEGRAM_ADMIN: "{{ lookup('env', 'TELEGRAM_ADMIN') }}"
    TELEGRAM_TOKEN: "{{ lookup('env', 'TELEGRAM_TOKEN') }}"
    
