---
- name: Ensure old versions of Docker are not installed.
  become: true
  package:
    name:
      - docker
      - docker-engine
    state: absent

- name: Ensure dependencies are installed.
  become: true
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg2
    state: present

- name: Add Docker apt key.
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  register: add_repository_key

- name: Ensure curl is present (on older systems without SNI).
  become: true
  package: name=curl state=present
  when: add_repository_key is failed

- name: Add Docker apt key (alternative for older systems without SNI).
  become: true
  shell: >
    curl -sSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  args:
    warn: false
  when: add_repository_key is failed

- name: Add Docker repository.
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present
    update_cache: true


- name: Check current docker-compose version.
  become: true
  command: docker-compose --version
  register: docker_compose_current_version
  changed_when: false
  failed_when: false

- name: Install docker-compose
  become: true
  apt:
    name: docker-compose
    state: present
    update_cache: yes
  tags:
    - docker

- name: Creates directory
  file:
    path: ~/postgres-compose
    state: directory

- name: Copy index test page
  become: true
  template:
    src: "files/docker-compose.yml"
    dest: "~/postgres-compose/docker-compose.yml"

- name: run postgres compose docker-compose.yml
  become: true
  docker_compose:
    project_src: "~/postgres-compose/docker-compose.yml"

# parts from here https://github.com/geerlingguy/ansible-role-docker/blob/master/tasks/setup-Debian.yml
