---
- name: Creates directory
  become: true
  file:
    path: ~/postgres-compose
    state: directory

- name: Copy index test page
  become: true
  template:
    src: "files/docker-compose.yml"
    dest: "~/postgres-compose/docker-compose.yml"

- name: run postgres compose docker-compose.yml
  become: true
  docker_compose:
    project_src: "~/postgres-compose/"

