
version: "3.7"
networks:
  prometheus: {}

volumes:
    prometheus_data: {}
    alertmanager_bot_data: {}
services:

  alertmanager-bot:
    command:
    - --alertmanager.url=http://{{ lookup('env', 'LOGGING_HOST') }}:9093
    - --log.level=info
    - --store=bolt
    - --bolt.path=/data/bot.db
    environment:
      TELEGRAM_ADMIN: {{ lookup('env','TELEGRAM_ADMIN') }}
      TELEGRAM_TOKEN: {{ lookup('env','TELEGRAM_TOKEN') }}
    image: metalmatze/alertmanager-bot:0.4.3
    networks:
    - prometheus
    ports:
    - 8080:8080
    restart: always
    volumes:
    - alertmanager_bot_data:/data


  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    links:
      - alertmanager:alertmanager
    networks:
      - prometheus
    restart: always


  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    networks:
      - prometheus
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'

