# docker-compose.yml
version: "3"
services:
  database:
    image: "postgres"
    environment:
      - POSTGRES_USER="${TYPEORM_USERNAME}"
      - POSTGRES_PASSWORD="${TYPEORM_PASSWORD}"
      - POSTGRES_DB="${TYPEORM_DATABASE}"
    ports:
      - "127.0.0.1:5532:5432"
